<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Own Counter' => 'Contador Próprio',
    'Stat' => 'Stat',
    'Ads' => 'Anúncios',
    'Cookie ID' => 'ID do Cookie',
    'Created At' => 'Criado em',
    'Direct' => 'Direto',
    'ID' => 'ID',
    'Inner' => 'Interno',
    'Ip Address' => 'Endereço IP',
    'Referrer' => 'Referencia',
    'Search' => 'Pesquisa',
    'Source' => 'Fonte',
    'Unknown' => 'Desconhecido',
    'Url' => 'Url',
    'User Agent' => 'Agente de Usuário',
    'WebStat Dashboard' => 'Configurações do sistema',
];
